### ISSUE TITLE
認知症老人の徘徊追跡ソフトウェア

### ISSUE THREAD

**Issue by DBSJM** [Lily-na/starlight#11]
施設・団体名　：　京都長寿の里　老人会
支援希望者　　：　長寿　祝
住所　　　　　：　京都市長寿町１００－１００
支援を希望する内容
認知症老人の行方不明が問題となっています。靴に取り付けたチップをGPSにて追跡し、
ご家族のスマートフォンで追跡できるシステムの製作をお願いできる方を探しています。

**Comment by nobesan** [comment]
延岡と申します。

GPS発信機を使ったシステム構築の経験が有ります。お役に立てそうですね。
[自己紹介](https://github.com/Lily-na/starlight/blob/gh-pages/nobeokatoshiya.md)

**Comment by DBSJM** [comment]
延岡　様

京都長寿の里　老人会　長寿　祝です。

ご連絡いただきありがとうございます。
ぜひご協力いただければと存じます。
打ち合わせをお願いしたいと思います。

**Comment by nobesan** [comment]
開発用のrepositoryを立ち上げました。

[開発用のrepository](https://github.com/nobesan/dbs2.git)

**Comment by nobesan** [comment]
開発完了しました。ご確認ください。

**Comment by DBSJM** [comment]
延岡様

長寿　祝です。
このたびはご協力いただきありがとうございました。
ソフトは活躍し、多くの職員がシステムを利用しその利便性に
助けられております。

ありがとうございました。
