### ISSUE TITLE
要介護者の健康管理システム開発

### ISSUE THREAD

**Issue by DBSJM** [Lily-na/starlight#15]
施設・団体名　：　国立老健センター
支援希望者　　：　多田出　願
住所　　　　　：　京都府京都市老健町１－１
支援を希望する内容
　要介護者は運動不足であることから末梢循環が悪くなる。
また寝返り回数が少ないと床ずれなどの生じることがある。
このため寝返り回数、ベットからの寝起き回数、歩行時間などを
手首につけたリングの情報から施設のPCへ収集するシステムの
開発を求む。

**Comment by ghost** [comment]
PHPであれば、2週間ほどでプロトタイプの作成が可能です。

下坂　光
starlight/Hikarishimosaka.md
[自己紹介](https://github.com/Lily-na/starlight/blob/gh-pages/Hikarishimosaka.md)

**Comment by DBSJM** [comment]
下坂　様

多田出　願です。
早速のご連絡ありがとうございます。
素晴らしい経歴の方で安心してお願いできます。
ご協力いただけるとのこと感謝いたします。
プロトタイプができればご連絡頂ければと存じます。

**Comment by ghost** [comment]
多田出 様

下記にて、プロトタイプのコード作成が完了しました。
[HikariShimosaka/HealthManagement](https://github.com/HikariShimosaka/HealthManagement)

一度、ご確認いただけますでしょうか。

**Comment by DBSJM** [comment]
下坂様

お世話になっております。
多田出です。
プロトタイプ確認いたしました。
センター職員一同感謝しております。
要介護者の健康増進に活用いたします。
誠にありがとうございます。
